-d /home/farhad/bin/gowin/uart/impl/gwsynthesis/uart.vg
-p GW1NR-9C-QFN88P-6
-pn GW1NR-LV9QN88PC6/I5
-cst /home/farhad/bin/gowin/uart/src/io.cst
-cfg /home/farhad/bin/gowin/uart/impl/pnr/device.cfg
-sdc /home/farhad/bin/gowin/uart/src/timing.sdc
-bit
-tr
-ph
-timing
-cst_error
-route_maxfan 23
